{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magic-link.fullname" . }}
  labels:
    {{- include "magic-link.labels" . | nindent 4 }}
type: Opaque
stringData:
  FASTMAIL_APP_PASSWORD: {{ required "config.fastmailAppPassword or existingSecret is required" .Values.config.fastmailAppPassword | quote }}
  SESSION_SECRET: {{ default (randAlphaNum 64) .Values.config.sessionSecret | quote }}
{{- end }}
